apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sink
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  kafka:
    pool: {{kafka-pool}}
    streams: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: aap-sink-db
            envVarPrefix: DB
  secureLogs:
    enabled: true
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
