database:
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  security: ${KAFKA_SECURITY_ENABLED}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH}
  keystorePath: ${KAFKA_KEYSTORE_PATH}
  credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}
  clientId: sink
